name: Check & Release

on:
  # Push to master will deploy a beta version
  push:
    branches:
      - master
  # A release via GitHub releases will deploy a latest version
  release:
    types: [ published ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v4
      -
        name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      -
        run: npm install
      -
        run: npm run lint


  # The deploy job is long but there are only 2 important parts. NPM publish
  # and triggering of docker image builds in the apify-actor-docker repo.
  deploy:
    name: Publish to NPM
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mbv'
      -
        # Determine if this is a beta or latest release
        name: Set Release Tag
        run: echo "RELEASE_TAG=$(if [ ${{ github.event_name }} = release ]; then echo latest; else echo beta; fi)" >> $GITHUB_ENV
      -
        # Check version consistency and increment pre-release version number for beta only.
        name: Bump pre-release version
        if: env.RELEASE_TAG == 'beta'
        run: node ./.github/scripts/before-beta-release.cjs
      -
        name: Install Dependencies
        run: npm install
      -
        name: Publish to NPM
        run: npm publish --tag ${{ env.RELEASE_TAG }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        # Latest version is tagged by the release process so we only tag beta here.
        name: Tag Version
        if: env.RELEASE_TAG == 'beta'
        run: |
          git_tag=v`node -p "require('./package.json').version"`
          git tag $git_tag
          git push origin $git_tag
